baseURL = ""
languageCode = "en-us"
# title = "Minimal"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Calin Tataru"
    profilePic = "images/E26514.jpg"
    description = "Kurz über Alexander Jann"
    githubUsername = "#"
    accent = "green"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:info@alexanderjann.de"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/rancyyd/"
    name = "fab fa-github"
    weight = 5

[[menu.icon]]
    url = "https://twitter.com/cyy_ran/"
    name = "fab fa-twitter"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/alexanderjann/"
    name = "fab fa-linkedin"
    weight = 3

[[menu.icon]]
    url = "https://www.xing.com/profile/Alexander_Jann"
    name = "fab fa-xing"
    weight = 4
